# Generated by Django 2.1 on 2018-10-04 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181004_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='commenter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
